version: '3.9'

services:
  backend:
    image: tfs-backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - 3000:3000

networks:
  default:
    name: tfs_network
    driver: bridge
