import {
  AlertTriangle,
  ArrowRight,
  Bell,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  Github,
  HelpCircle,
  Image,
  Keyboard,
  Laptop,
  Loader2,
  LogOut,
  type LucideIcon,
  Menu,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  Add: Plus,
  ArrowRight: ArrowRight,
  Bell: Bell,
  Billing: CreditCard,
  Check: Check,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Close: X,
  Ellipsis: MoreVertical,
  Github: Github,
  Help: HelpCircle,
  Keyboard: Keyboard,
  Laptop: Laptop,
  Logo: Command,
  Logout: LogOut,
  Media: Image,
  Menu: Menu,
  Moon: Moon,
  Page: File,
  Pizza: Pizza,
  Post: FileText,
  Settings: Settings,
  Spinner: Loader2,
  Sun: SunMedium,
  Trash: Trash,
  Twitter: Twitter,
  User: User,
  Warning: AlertTriangle,
};
